# Generated by Django 4.1.5 on 2023-01-16 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message="Регистрация с домена 'rambler.ru' запрещена", regex='@rambler.ru')]),
        ),
    ]
