# Generated by Django 4.1.5 on 2023-01-16 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='mail@mail.ru', max_length=254, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message="Регистрация с домена 'rambler.ru' запрещена", regex='@rambler.ru')]),
            preserve_default=False,
        ),
    ]
