# Generated by Django 4.1.5 on 2023-01-16 13:19

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='2010-10-10', validators=[users.validators.check_user_age]),
        ),
    ]
