# Generated by Django 4.1.5 on 2023-01-16 13:23

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(validators=[users.validators.check_user_age]),
        ),
    ]
