# Generated by Django 4.1.5 on 2023-01-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='cat', max_length=10),
            preserve_default=False,
        ),
    ]
