# Generated by Django 4.1.5 on 2023-01-15 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
