# Generated by Django 4.1.5 on 2023-01-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0008_alter_advertisement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
